JSON=../json/single_include
Z3=../z3
Z3LIBPATH=$(Z3)/build
Z3LIB=$(Z3LIBPATH)/libz3.so
AUTOCHECK=../autocheck/include
CATCH2=../Catch2/single_include

# output binary
BIN := sere_tests #nfasl_tests

TESTS := sere_tests #nfasl_tests

# source files
SERE_SRCS :=        	\
    Language.cpp    	\
	Z3.cpp          	\
	rt/RtPredicate.cpp 	\
	rt/RtNfasl.cpp	 	\
	Nfasl.cpp       	\
	BisimNfasl.cpp

SERE_TESTS_SRCS :=       \
	test/EvalBoolExpr.cpp	 \
	test/EvalNfasl.cpp	 \
	test/EvalRtNfasl.cpp \
	test/EvalSere.cpp	 \
	test/GenNfasl.cpp	 \
	test/Letter.cpp		 \
	test/Main.cpp		 \
	test/TestNfasl.cpp	 \
	test/TestRtNfasl.cpp \
	test/TestSere.cpp	 \
	test/ToolsZ3.cpp     \
	$(SERE_SRCS)

SRCS := $(SERE_SRCS) $(SERE_TESTS_SRCS)

# files included in the tarball generated by 'make dist' (e.g. add LICENSE file)
DISTFILES := $(BIN)

# filename of the tar archive generated by 'make dist'
DISTOUTPUT := $(BIN).tar.gz

# intermediate directory for generated object files
OBJDIR := .o
# intermediate directory for generated dependency files
DEPDIR := .d

# object files, auto generated from source files
OBJS := $(patsubst %,$(OBJDIR)/%.o,$(basename $(SRCS)))
SERE_TESTS_OBJS := $(patsubst %,$(OBJDIR)/%.o,$(basename $(SERE_TESTS_SRCS)))
# dependency files, auto generated from source files
DEPS := $(patsubst %,$(DEPDIR)/%.d,$(basename $(SRCS)))

# compilers (at least gcc and clang) don't create the subdirectories automatically
$(shell mkdir -p $(dir $(OBJS)) >/dev/null)
$(shell mkdir -p $(dir $(DEPS)) >/dev/null)

# C compiler
CC := gcc
# C++ compiler
CXX := g++
# linker
LD := g++
# tar
TAR := tar

# C flags
CFLAGS :=
# C++ flags
CXXFLAGS :=  -std=c++17 -I. -I$(JSON) -I$(Z3)/src/api -I$(AUTOCHECK) -I$(CATCH2)
# C/C++ flags
CPPFLAGS := -g -Wall -Wextra -pedantic  -lpthread
# linker flags
LDFLAGS :=

LDLIBS := $(Z3LIB) -lgtest -lpthread -Wl,-rpath,$(Z3LIBPATH)
# flags required for dependency generation; passed to compilers
DEPFLAGS = -MT $@ -MD -MP -MF $(DEPDIR)/$*.Td

# compile C source files
COMPILE.c = $(CC) $(DEPFLAGS) $(CFLAGS) $(CPPFLAGS) -c -o $@
# compile C++ source files
COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) -c -o $@
# link object files to binary
LINK.o = $(LD) -o $@ $(LDFLAGS)
# precompile step
PRECOMPILE =
# postcompile step
POSTCOMPILE = mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d

all: $(BIN)

dist: $(DISTFILES)
	$(TAR) -cvzf $(DISTOUTPUT) $^

.PHONY: clean
clean:
	$(RM) -r $(OBJDIR) $(DEPDIR)

.PHONY: distclean
distclean: clean
	$(RM) $(BIN) $(DISTOUTPUT)

.PHONY: install
install:
	@echo no install tasks configured

.PHONY: uninstall
uninstall:
	@echo no uninstall tasks configured

.PHONY: check
check: $(BIN)
	LD_LIBRARY_PATH=$(Z3LIBPATH) ./sere_tests
#	LD_LIBRARY_PATH=$(Z3LIBPATH) ./nfasl_tests

gdb: $(BIN)
	LD_LIBRARY_PATH=$(Z3LIBPATH) gdb ./sere_tests

.PHONY: help
help:
	@echo available targets: all dist clean distclean install uninstall check

sere_tests: $(SERE_TESTS_OBJS)
	$(LINK.o) $^  $(LDLIBS)

nfasl_tests: $(NFASL_TESTS_OBJS)
	$(LINK.o) $^  $(LDLIBS)

$(OBJDIR)/%.o: %.c
$(OBJDIR)/%.o: %.c $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.c) $<
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.cpp
$(OBJDIR)/%.o: %.cpp $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.cc
$(OBJDIR)/%.o: %.cc $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

$(OBJDIR)/%.o: %.cxx
$(OBJDIR)/%.o: %.cxx $(DEPDIR)/%.d
	$(PRECOMPILE)
	$(COMPILE.cc) $<
	$(POSTCOMPILE)

.PRECIOUS: $(DEPDIR)/%.d
$(DEPDIR)/%.d: ;

-include $(DEPS)
